### ISSUE TITLE
Changes required in Footer

### ISSUE THREAD

**Issue by JaideepGuntupalli** [huddl-it/huddl.it#11]
Todo:
- [ ] Add same hover effect as in header in footer
- [ ] Update class name to suit both use cases
- [ ] Update copyright text color

**Comment by jayeshs08** [comment]
@JaideepGuntupalli I would like to work on this. Kindly assign this to me.

**Comment by JaideepGuntupalli** [comment]
Hey @jayeshs08 so sorry but our team members are already working on them I forgot to assign them but thanks for the interest. I will tag you if any help is needed.
