### ISSUE TITLE
Add new question as placeholder

### ISSUE THREAD

**Issue by JaideepGuntupalli** [huddl-it/huddl.it#13]
Todo:
- [ ] Add new question as placeholder about any other person
- [ ] Fix Jaideep's title

**Comment by jayeshs08** [comment]
@JaideepGuntupalli I would like to work on this ! Kindly assign this to me.

**Comment by phoenix1881** [comment]
Working on this

**Comment by JaideepGuntupalli** [comment]
Hey @jayeshs08 so sorry but our team members are already working on them I forgot to assign them but thanks for the interest. I will tag you if any help is needed.
